"""Compute-node topology discovery for parallel-optimization decisions.

``hpc.cluster.topo`` answers the question the login-node whitelist
deliberately cannot: *what hardware will my job actually run on?*  CPU model,
sockets/cores/threads, SIMD capability, NUMA domains, cache hierarchy and
node memory -- the facts needed to pick ``--ntasks-per-node``,
``--cpus-per-task``, MPI binding and ``OMP_NUM_THREADS``.

Two data sources are combined:

* ``sinfo`` on the login node (already whitelisted, LOW cost tier): partition
  sizes, CPUs/memory per node, features and GRES -- Slurm's own view, no job
  needed.
* a **fixed, server-generated** probe script run as a tiny one-CPU job on a
  compute node: ``lscpu`` / ``/proc/cpuinfo`` / ``numactl --hardware`` /
  ``/proc/meminfo``.  The agent supplies *no part* of that script, and the
  script never calls ``squeue``/``sacct``/``scontrol``: only node-local
  hardware facts are read, so no other user's job metadata can reach this
  process (the same shared-account isolation rule that forbids those tools on
  the login node).

Results are cached twice: in-process for this session, and remotely as a JSON
file under ``$ROOT/.hpc-mcp/topo/`` so later sessions re-use a static hardware
probe instead of queueing another job.  ``refresh=true`` forces a re-probe.
"""

from __future__ import annotations

import asyncio
import json
import re
import time
from typing import Any

from ..config import Config
from ..errors import HpcMcpError, RemoteCommandError, SlurmPolicyError
from ..filesystem.service import FileService
from ..shell.safe_exec import SafeExec
from ..slurm.manager import SlurmManager

#: Partition field list for the summary query.  ``::`` is used as the field
#: separator because the login-node command policy rejects ``|`` outright.
SINFO_PARTITION_FORMAT = "%P::%a::%D::%c::%m::%f::%G::%l::%T"
#: Per-node field list (identical hardware collapses into one variant row).
SINFO_NODE_FORMAT = "%c::%m::%f::%G::%t"

PROBE_JOB_NAME = "hpc-mcp-topo"
TOPO_DIRNAME = ".hpc-mcp/topo"
PROBE_SCRIPT_NAME = "collect_topo.sh"

#: Section markers emitted by the probe script.
SECTION_PREFIX = "::hpc-mcp:"

#: Max bytes of probe stdout parsed (lscpu output is a few KiB).
_PROBE_OUTPUT_LIMIT = 256 * 1024

#: Terminal states that mean "the probe ran"; everything else is a failure.
_OK_STATES = frozenset({"COMPLETED"})
_BAD_STATES = frozenset(
    {"FAILED", "CANCELLED", "TIMEOUT", "OUT_OF_MEMORY", "NODE_FAIL", "PREEMPTED", "BOOT_FAIL", "DEADLINE"}
)

#: Partitions accepted by this tool.  Stricter than the generic Slurm policy
#: on purpose: the name is interpolated into ``sinfo -p`` and into the cache
#: file name, so only a conservative character set is allowed.
_SAFE_PARTITION_RE = re.compile(r"^[A-Za-z0-9_.\-]{1,128}$")

#: The probe script is FIXED content -- nothing from the agent is ever
#: interpolated into it.  It reads node-local hardware facts only; it must
#: never query the queue (squeue/sacct/scontrol), because under a shared
#: account that would leak other users' job metadata into the MCP process.
PROBE_SCRIPT = f"""#!/bin/bash
# hpc-mcp compute-node topology probe.
# Generated by hpc-mcp -- FIXED content: no tool argument is interpolated.
# Reads node-local hardware facts only; never queries the job queue.
export LC_ALL=C LANG=C
echo '{SECTION_PREFIX}meta'
echo "SLURMD_NODENAME=${{SLURMD_NODENAME:-unknown}}"
echo "SLURM_JOB_NODELIST=${{SLURM_JOB_NODELIST:-unknown}}"
echo "SLURM_CPUS_ON_NODE=${{SLURM_CPUS_ON_NODE:-unknown}}"
echo "SLURM_MEM_PER_NODE=${{SLURM_MEM_PER_NODE:-unknown}}"
echo '{SECTION_PREFIX}lscpu'
if command -v lscpu >/dev/null 2>&1; then lscpu; else echo 'unavailable lscpu'; fi
echo '{SECTION_PREFIX}cpuinfo'
if [ -r /proc/cpuinfo ]; then grep -E '^[A-Za-z][A-Za-z0-9 _()./-]*:' /proc/cpuinfo | head -n 200; else echo 'unavailable cpuinfo'; fi
echo '{SECTION_PREFIX}numactl'
if command -v numactl >/dev/null 2>&1; then numactl --hardware 2>/dev/null || echo 'unavailable numactl'; else echo 'unavailable numactl'; fi
echo '{SECTION_PREFIX}meminfo'
if [ -r /proc/meminfo ]; then grep -E '^(MemTotal|MemFree|MemAvailable|SwapTotal|Hugepagesize|HugePages_Total|NUMA_)' /proc/meminfo; else echo 'unavailable meminfo'; fi
echo '{SECTION_PREFIX}syscache'
if [ -d /sys/devices/system/cpu/cpu0/cache ]; then
  for index in /sys/devices/system/cpu/cpu0/cache/index*; do
    if [ -r "$index/level" ]; then
      printf '%s %s %s %s\\n' "$(cat "$index/level")" "$(cat "$index/type")" "$(cat "$index/size")" "$(cat "$index/shared_cpu_list" 2>/dev/null)"
    fi
  done
else
  echo 'unavailable syscache'
fi
echo '{SECTION_PREFIX}os'
uname -s
uname -m
uname -r
echo '{SECTION_PREFIX}end'
"""


# ---------------------------------------------------------------------------
# Parsing helpers (pure functions -- unit-testable without SSH)
# ---------------------------------------------------------------------------

_SIZE_RE = re.compile(r"^([\d.]+)\s*([KMGT]?)i?B?\b", re.IGNORECASE)
_SIZE_MULTIPLIER_KIB = {"": 1, "K": 1, "M": 1024, "G": 1024 * 1024, "T": 1024 * 1024 * 1024}

#: SIMD / vector-ISA flags worth surfacing for compiler and math-library
#: choices.  Everything else in the (long) ``Flags`` line is ignored.
SIMD_FLAGS: tuple[str, ...] = (
    "sse4_2", "avx", "avx2", "fma", "f16c",
    "avx512f", "avx512cd", "avx512bw", "avx512dq", "avx512vl",
    "avx512_vnni", "avx512vnni", "avx512_bf16", "avx512vbmi", "avx512_vpopcntdq",
    "amx_tile", "amx_bf16", "amx_int8", "avx_vnni",
    "sve", "sve2", "neon", "asimd", "vsx", "altivec",
)


def parse_size_to_kib(value: str | None) -> int | None:
    """Parse ``32K`` / ``1.5 MiB`` style sizes into KiB (float-tolerant)."""
    if not value:
        return None
    m = _SIZE_RE.match(value.strip())
    if not m:
        return None
    number = float(m.group(1))
    unit = m.group(2).upper()
    return int(number * _SIZE_MULTIPLIER_KIB[unit])


def count_cpu_list(spec: str | None) -> int | None:
    """Count CPUs in a CPU list such as ``0-15,32-47`` or ``0 1 2 3``.

    Both separators occur in practice: lscpu prints comma-separated ranges,
    ``numactl --hardware`` prints space-separated single CPUs.
    """
    if not spec:
        return None
    total = 0
    for part in re.split(r"[\s,]+", spec.strip()):
        if not part:
            continue
        if "-" in part:
            low, _, high = part.partition("-")
            if low.strip().isdigit() and high.strip().isdigit():
                total += max(0, int(high) - int(low) + 1)
        elif part.isdigit():
            total += 1
    return total or None


def _as_int(value: str | None) -> int | None:
    if value is None:
        return None
    m = re.match(r"^-?\d+", value.strip())
    return int(m.group(0)) if m else None


def _kv_lines(text: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        if key:
            pairs.append((key, value.strip()))
    return pairs


def _env_lines(text: str) -> dict[str, str]:
    """Parse ``KEY=value`` blocks emitted by the probe script's meta section."""
    out: dict[str, str] = {}
    for raw in text.splitlines():
        if "=" not in raw:
            continue
        key, _, value = raw.partition("=")
        key = key.strip()
        if key:
            out[key] = value.strip()
    return out


def split_sections(text: str) -> dict[str, str]:
    """Split probe stdout into ``{section_name: body}``."""
    sections: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines():
        if line.startswith(SECTION_PREFIX):
            current = line[len(SECTION_PREFIX):].strip()
            sections.setdefault(current, [])
            continue
        if current is not None:
            sections[current].append(line)
    return {name: "\n".join(body).strip("\n") for name, body in sections.items()}


def parse_lscpu(text: str) -> dict[str, Any]:
    """Parse ``lscpu`` text (LANG=C) into structured CPU facts."""
    if "unavailable lscpu" in text:
        return {}
    pairs = _kv_lines(text)
    if not pairs:
        return {}
    low: dict[str, str] = {}
    for key, value in pairs:
        low[key.lower()] = value
    numa_cpus: dict[int, str] = {}
    for key, value in pairs:
        m = re.match(r"^numa node(\d+) cpu\(s\)$", key.lower())
        if m:
            numa_cpus[int(m.group(1))] = value

    def cache(*names: str) -> int | None:
        for name in names:
            if name in low:
                return parse_size_to_kib(low[name])
        return None

    sockets = _as_int(low.get("socket(s)"))
    cores_per_socket = _as_int(low.get("core(s) per socket"))
    threads_per_core = _as_int(low.get("thread(s) per core"))
    logical = _as_int(low.get("cpu(s)"))
    numa_count = _as_int(low.get("numa node(s)"))
    physical: int | None = None
    if sockets and cores_per_socket:
        physical = sockets * cores_per_socket
    elif logical and threads_per_core:
        physical = max(1, logical // threads_per_core)

    return {
        "model_name": low.get("model name") or low.get("bios model name"),
        "vendor": low.get("vendor id"),
        "architecture": low.get("architecture"),
        "byte_order": low.get("byte order"),
        "sockets": sockets,
        "cores_per_socket": cores_per_socket,
        "threads_per_core": threads_per_core,
        "physical_cores": physical,
        "logical_cpus": logical,
        "online_cpus": low.get("on-line cpu(s) list"),
        "numa_nodes": numa_count if numa_count is not None else (len(numa_cpus) or None),
        "numa_cpu_lists": {str(k): v for k, v in sorted(numa_cpus.items())},
        "cpu_mhz": _as_float(low.get("cpu mhz")),
        "cpu_max_mhz": _as_float(low.get("cpu max mhz")),
        "cpu_min_mhz": _as_float(low.get("cpu min mhz")),
        "hypervisor": low.get("hypervisor vendor"),
        "virtualization": low.get("virtualization"),
        "cache_kib": {
            "l1d": cache("l1d cache", "l1d"),
            "l1i": cache("l1i cache", "l1i"),
            "l2": cache("l2 cache", "l2"),
            "l3": cache("l3 cache", "l3"),
        },
        "cache_raw": {
            "l1d": low.get("l1d cache") or low.get("l1d"),
            "l1i": low.get("l1i cache") or low.get("l1i"),
            "l2": low.get("l2 cache") or low.get("l2"),
            "l3": low.get("l3 cache") or low.get("l3"),
        },
        "flags": low.get("flags") or low.get("features"),
    }


def _as_float(value: str | None) -> float | None:
    if value is None:
        return None
    m = re.match(r"^-?\d+(?:\.\d+)?", value.strip())
    return float(m.group(0)) if m else None


def parse_cpuinfo(text: str) -> dict[str, Any]:
    """Parse the first block of ``/proc/cpuinfo`` (fallback when no lscpu)."""
    if "unavailable cpuinfo" in text or not text.strip():
        return {}
    blocks = [b for b in re.split(r"\n\s*\n", text.strip()) if b.strip()]
    for block in blocks:
        fields: dict[str, str] = {}
        for raw in block.splitlines():
            if ":" not in raw:
                continue
            key, _, value = raw.partition(":")
            fields[key.strip().lower()] = value.strip()
        if not fields:
            continue
        return {
            "model_name": fields.get("model name") or fields.get("processor") or fields.get("hardware"),
            "vendor": fields.get("vendor_id") or fields.get("cpu implementer"),
            "cpu_part": fields.get("cpu part"),
            "siblings": _as_int(fields.get("siblings")),
            "cpu_cores": _as_int(fields.get("cpu cores")),
            "physical_id": _as_int(fields.get("physical id")),
            "flags": fields.get("flags") or fields.get("features"),
        }
    return {}


def parse_numactl(text: str) -> dict[str, Any]:
    """Parse ``numactl --hardware`` output (NUMA sizes, CPU lists, distances)."""
    if "unavailable numactl" in text or not text.strip():
        return {}
    nodes: dict[int, dict[str, Any]] = {}
    distances: list[list[int]] = []
    available: int | None = None
    in_distances = False
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        m = re.match(r"^available:\s*(\d+)\s*nodes?", line)
        if m:
            available = int(m.group(1))
            in_distances = False
            continue
        m = re.match(r"^node\s+(\d+)\s+cpus:\s*(.*)$", line)
        if m:
            nodes.setdefault(int(m.group(1)), {})["cpus"] = m.group(2).strip() or None
            in_distances = False
            continue
        m = re.match(r"^node\s+(\d+)\s+size:\s*(\d+)\s*MB", line)
        if m:
            nodes.setdefault(int(m.group(1)), {})["size_mb"] = int(m.group(2))
            in_distances = False
            continue
        m = re.match(r"^node\s+(\d+)\s+free:\s*(\d+)\s*MB", line)
        if m:
            nodes.setdefault(int(m.group(1)), {})["free_mb"] = int(m.group(2))
            in_distances = False
            continue
        if line.startswith("node distances:"):
            in_distances = True
            continue
        if in_distances:
            m = re.match(r"^(\d+):\s*(.*)$", line)
            if m:
                distances.append([int(tok) for tok in m.group(2).split() if tok.isdigit()])
    out_nodes = []
    for index in sorted(nodes):
        entry = nodes[index]
        out_nodes.append(
            {
                "node": index,
                "cpus": entry.get("cpus"),
                "cpus_count": count_cpu_list(entry.get("cpus")),
                "size_mb": entry.get("size_mb"),
                "free_mb": entry.get("free_mb"),
            }
        )
    return {"count": available if available is not None else (len(nodes) or None), "nodes": out_nodes, "distances": distances}


def parse_meminfo(text: str) -> dict[str, int]:
    """Parse selected ``/proc/meminfo`` fields into MiB values."""
    out: dict[str, int] = {}
    for raw in text.splitlines():
        if ":" not in raw:
            continue
        key, _, value = raw.partition(":")
        m = re.match(r"^(\d+)\s*kB", value.strip())
        if m:
            out[key.strip().lower()] = int(m.group(1)) // 1024
    return out


def parse_sysfs_cache(text: str) -> dict[str, int]:
    """Parse the ``/sys/devices/system/cpu/cpu0/cache`` dump into KiB sizes.

    Older ``lscpu`` builds (and several ARM platforms, e.g. Phytium FT2000+)
    print no cache lines at all, which is exactly where this fallback is the
    only source of the cache hierarchy.
    """
    out: dict[str, int] = {}
    kind_suffix = {"data": "d", "instruction": "i", "unified": ""}
    for raw in text.splitlines():
        parts = raw.split()
        if len(parts) < 3:
            continue
        level, kind, size = parts[0].strip(), parts[1].strip().lower(), parts[2]
        if not level.isdigit():
            continue
        kib = parse_size_to_kib(size)
        if kib is None:
            continue
        key = f"l{level}{kind_suffix.get(kind, '')}"
        # cpu0's view repeats shared caches per CPU; keep the largest seen.
        out[key] = max(kib, out.get(key, 0))
    return out


def summarize_simd(flags: str | None) -> dict[str, Any]:
    """Reduce a CPU flags string to the vector-ISA facts that matter."""
    if not flags:
        return {"level": None, "present": {}, "flags_count": 0}
    tokens = {tok for tok in re.split(r"[\s,]+", flags.lower()) if tok}
    present = {name: (name in tokens) for name in SIMD_FLAGS}
    if "avx512f" in tokens:
        level = "avx512"
    elif "avx2" in tokens:
        level = "avx2"
    elif "avx" in tokens:
        level = "avx"
    elif "sse4_2" in tokens:
        level = "sse4.2"
    elif tokens & {"sve", "sve2"}:
        level = "arm-sve"
    elif tokens & {"neon", "asimd"}:
        level = "arm-neon"
    elif tokens & {"vsx", "altivec"}:
        level = "power-vsx"
    else:
        level = "baseline"
    return {
        "level": level,
        "present": {name: True for name, ok in present.items() if ok},
        "flags_count": len(tokens),
    }


def parse_sinfo_partitions(text: str) -> list[dict[str, Any]]:
    """Parse the partition-summary ``sinfo`` query (one row per partition)."""
    rows: list[dict[str, Any]] = []
    for line in text.splitlines():
        parts = [p.strip() for p in line.split("::")]
        if len(parts) < 9:
            continue
        name = parts[0].rstrip("*")
        if not name:
            continue
        rows.append(
            {
                "partition": name,
                "default": parts[0].endswith("*"),
                "availability": _none_if_placeholder(parts[1]),
                "nodes": _as_int(parts[2]),
                "cpus_per_node": _as_int(parts[3]),
                "memory_per_node_mb": _as_int(parts[4]),
                "features": _none_if_placeholder(parts[5]),
                "gres": _none_if_placeholder(parts[6]),
                "time_limit": _none_if_placeholder(parts[7]),
                "state": _none_if_placeholder(parts[8]),
            }
        )
    return rows


def parse_sinfo_nodes(text: str) -> tuple[list[dict[str, Any]], int]:
    """Collapse the per-node ``sinfo`` rows into distinct hardware variants.

    Returns ``(variants, rows_seen)``.  A big homogeneous partition therefore
    yields a single variant row instead of thousands.

    Node *state* is deliberately **not** part of the variant key: allocation
    state (idle/alloc/drain/down) changes minute to minute and would otherwise
    turn every partition into a fake "heterogeneous hardware" warning.  States
    are reported per variant as a histogram instead.
    """
    variants: dict[tuple, dict[str, Any]] = {}
    rows = 0
    for line in text.splitlines():
        parts = [p.strip() for p in line.split("::")]
        if len(parts) < 5:
            continue
        rows += 1
        cpus, memory, features, gres, state = (parts[0], parts[1], parts[2], parts[3], parts[4])
        key = (cpus, memory, features, gres)
        entry = variants.get(key)
        if entry is None:
            entry = {
                "cpus": _as_int(cpus),
                "memory_mb": _as_int(memory),
                "features": _none_if_placeholder(features),
                "gres": _none_if_placeholder(gres),
                "nodes": 0,
                "states": {},
            }
            variants[key] = entry
        entry["nodes"] += 1
        state_name = _none_if_placeholder(state) or "unknown"
        entry["states"][state_name] = entry["states"].get(state_name, 0) + 1
    ordered = sorted(variants.values(), key=lambda v: (-int(v["nodes"]), str(v.get("cpus"))))
    for entry in ordered:
        entry["states"] = dict(sorted(entry["states"].items(), key=lambda kv: (-kv[1], kv[0])))
    return ordered, rows


def _none_if_placeholder(value: str | None) -> str | None:
    if value is None:
        return None
    text = value.strip()
    if not text or text.lower() in {"(null)", "n/a", "none", "unknown"}:
        return None
    return text


def recommend_parallel(
    cpu: dict[str, Any],
    numa: dict[str, Any],
    memory: dict[str, int],
    *,
    sinfo_partition: dict[str, Any] | None,
    slurm_max_cpus: int,
    slurm_max_nodes: int,
    slurm_max_time: str,
) -> dict[str, Any]:
    """Derive first-cut Slurm/MPI/OpenMP parameters from the topology.

    These are *heuristics*, not measurements: they encode the standard
    placement rules (one rank per physical core, one rank per NUMA domain
    when hybrid, no over-subscription of hyperthreads) so the agent starts
    from a sane point instead of guessing.
    """
    notes: list[str] = []
    raw_threads = cpu.get("threads_per_core")
    threads_known = isinstance(raw_threads, int) and raw_threads > 0
    threads_per_core = raw_threads if threads_known else 1
    sockets = cpu.get("sockets")
    cores_per_socket = cpu.get("cores_per_socket")
    logical = cpu.get("logical_cpus") or (sinfo_partition or {}).get("cpus_per_node")
    if not isinstance(logical, int) or logical <= 0:
        logical = None

    physical = cpu.get("physical_cores")
    if not isinstance(physical, int) or physical <= 0:
        if logical and threads_known:
            physical = max(1, logical // threads_per_core)
        elif logical:
            physical = logical
            notes.append(
                "没有 lscpu 数据：物理核数按 Slurm 报告的每节点逻辑核数估计（SMT/超线程状态未知），"
                "rank 数请结合实测确认。"
            )
    if physical is None:
        return {
            "available": False,
            "notes": [
                "No CPU topology data was collected (lscpu and /proc/cpuinfo both unavailable); "
                "fall back to the partition-level numbers in this response."
            ],
        }

    numa_count = numa.get("count") or cpu.get("numa_nodes") or 1
    if not isinstance(numa_count, int) or numa_count < 1:
        numa_count = 1

    simd_level = (cpu.get("simd") or {}).get("level")

    pure_mpi_flags = ["--cpu-bind=cores"]
    if threads_per_core and threads_per_core > 1:
        pure_mpi_flags.insert(0, "--hint=nomultithread")
        notes.append(
            f"节点有 {threads_per_core} 线程/物理核（SMT 开启）：把 MPI rank 数限制在物理核数（{physical}），"
            "并加 --hint=nomultithread，避免两个 rank 共享同一物理核争抢向量单元。"
        )

    hybrid_ranks = numa_count if (numa_count > 1 and physical % numa_count == 0) else 1
    hybrid_threads = max(1, physical // hybrid_ranks)
    if hybrid_ranks > 1:
        notes.append(
            f"检测到 {numa_count} 个 NUMA 域：混合模式下建议每 NUMA 域 1 个 rank（共 {hybrid_ranks} 个/节点），"
            "让每个 rank 的内存与线程都落在本域内，避免跨域访存。"
        )
    else:
        notes.append("单 NUMA 域：无需跨域绑定，按物理核铺满 rank 即可。")

    if simd_level == "avx512":
        notes.append("CPU 支持 AVX-512：编译时用 -march=native / -xCORE-AVX512 可显著加速向量化内核（注意降频风险）。")
    elif simd_level == "avx2":
        notes.append("CPU 支持 AVX2/FMA：编译时用 -march=native / -xCORE-AVX2 让内核走 FMA 向量路径。")
    elif simd_level in {"arm-neon", "arm-sve"}:
        notes.append(f"ARM 向量单元 {simd_level}：编译器默认开启，注意 math 库（ArmPL/OpenBLAS）与线程亲和设置。")
    if simd_level is None:
        notes.append("未取到 SIMD 指令集信息（lscpu 的 Flags 不可用），无法给出编译期 -march 建议。")

    mem_total_mib = memory.get("memtotal")
    if not isinstance(mem_total_mib, int) or mem_total_mib <= 0:
        mem_total_mib = (sinfo_partition or {}).get("memory_per_node_mb")
    suggested_mem_mib = int(mem_total_mib * 0.9) if isinstance(mem_total_mib, int) and mem_total_mib > 0 else None
    if suggested_mem_mib:
        notes.append(
            f"每节点可用内存约 {mem_total_mib} MiB：建议 --mem≈{suggested_mem_mib}M（留 10% 给系统），"
            "并按 rank 数换算每 rank 内存上限，避免 OOM 被 Slurm 杀掉。"
        )

    max_nodes_for_cpus = max(1, slurm_max_cpus // physical) if physical else 1
    if max_nodes_for_cpus < slurm_max_nodes:
        notes.append(
            f"服务端 max_cpus={slurm_max_cpus} 会在 {max_nodes_for_cpus} 个节点（{physical} 核/节点）时触顶，"
            f"即使 max_nodes={slurm_max_nodes} 更大；扩展规模前先确认这个上限。"
        )

    return {
        "available": True,
        "basis": {
            "physical_cores_per_node": physical,
            "logical_cpus_per_node": logical,
            "threads_per_core": threads_per_core,
            "sockets_per_node": sockets,
            "cores_per_socket": cores_per_socket,
            "numa_domains": numa_count,
            "simd_level": simd_level,
        },
        "pure_mpi": {
            "ntasks_per_node": physical,
            "cpus_per_task": 1,
            "slurm_flags": pure_mpi_flags,
            "mpi_launcher": "mpirun -map-by core --bind-to core",
        },
        "hybrid_mpi_omp": {
            "ranks_per_node": hybrid_ranks,
            "cpus_per_task": hybrid_threads,
            "env": {
                "OMP_NUM_THREADS": str(hybrid_threads),
                "OMP_PROC_BIND": "close",
                "OMP_PLACES": "cores",
            },
            "mpi_launcher": "mpirun -map-by numa --bind-to numa" if hybrid_ranks > 1 else "mpirun -map-by core --bind-to core",
        },
        "openmp_only": {
            "cpus_per_task": physical,
            "slurm_flags": ["--hint=nomultithread"] if threads_per_core > 1 else [],
            "env": {
                "OMP_NUM_THREADS": str(physical),
                "OMP_PROC_BIND": "close",
                "OMP_PLACES": "cores",
            },
        },
        "memory": {
            "per_node_mib": mem_total_mib if isinstance(mem_total_mib, int) else None,
            "suggested_mem_per_node_mib": suggested_mem_mib,
        },
        "server_limits": {
            "max_cpus": slurm_max_cpus,
            "max_nodes": slurm_max_nodes,
            "max_time": slurm_max_time,
            "nodes_reaching_max_cpus": max_nodes_for_cpus,
        },
        "notes": notes,
    }


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------

class TopologyService:
    """Collect and cache compute-node topology facts."""

    def __init__(
        self,
        cfg: Config,
        files: FileService,
        safe_exec: SafeExec,
        slurm: SlurmManager,
    ) -> None:
        self._cfg = cfg
        self._files = files
        self._safe_exec = safe_exec
        self._slurm = slurm
        self._lock = asyncio.Lock()
        self._memory: dict[str, tuple[float, dict[str, Any]]] = {}
        self._pending: dict[str, dict[str, Any]] = {}

    # -- public API -----------------------------------------------------------

    async def probe(self, *, partition: str | None = None, refresh: bool = False) -> dict[str, Any]:
        """Return topology facts for ``partition`` (cached when fresh)."""
        async with self._lock:
            part = self._resolve_partition(partition)
            ttl = float(self._cfg.topology.cache_ttl_seconds)
            if not refresh:
                hit = self._memory_lookup(part, ttl)
                if hit is not None:
                    payload, age = hit
                    return {**payload, "source": "session-cache", "cache_age_seconds": round(age, 1)}
                remote = await self._remote_cache_lookup(part, ttl)
                if remote is not None:
                    self._memory_put(part, remote)
                    return {**remote, "source": "remote-cache"}
            else:
                await self._drop_pending(part, cancel=True)

            pending = self._pending.get(part)
            if pending is not None and not refresh:
                resumed = await self._resume_pending(part, pending)
                if resumed is not None:
                    return resumed
            return await self._collect(part)

    def invalidate(self) -> None:
        """Drop in-process caches (called after agent-driven reconfiguration)."""
        self._memory.clear()

    # -- internals ------------------------------------------------------------

    def _resolve_partition(self, partition: str | None) -> str:
        allowed = self._cfg.slurm.allowed_partitions
        if not allowed:
            raise SlurmPolicyError(
                "No Slurm partitions are allowed by the server configuration, so no compute node "
                "can be probed. Ask the administrator to set slurm.allowed_partitions (fail-closed default)."
            )
        if partition is None:
            # The configured default goes through the same identifier check as
            # a requested one: the name is interpolated into ``sinfo -p`` and
            # into the cache filename, so a hand-edited config must not be able
            # to smuggle anything in (fail-closed).
            partition = allowed[0]
        if not isinstance(partition, str) or not _SAFE_PARTITION_RE.match(partition):
            raise SlurmPolicyError(
                "Partition must be a simple name (letters, digits, '.', '-', '_')",
                requested="(redacted)",
            )
        if partition not in allowed:
            raise SlurmPolicyError(
                "Requested partition is not allowed by the server policy",
                requested="(redacted)",
            )
        return partition

    @property
    def _topo_dir(self) -> str:
        return f"{self._cfg.root.rstrip('/')}/{TOPO_DIRNAME}"

    @property
    def _script_path(self) -> str:
        return f"{self._topo_dir}/{PROBE_SCRIPT_NAME}"

    def _cache_path(self, partition: str) -> str:
        safe = re.sub(r"[^A-Za-z0-9_.-]", "_", partition)[:64]
        return f"{self._topo_dir}/topology_{safe}.json"

    def _memory_lookup(self, partition: str, ttl: float) -> tuple[dict[str, Any], float] | None:
        entry = self._memory.get(partition)
        if not entry:
            return None
        stored_at, payload = entry
        age = time.time() - stored_at
        if ttl <= 0 or age > ttl:
            self._memory.pop(partition, None)
            return None
        return payload, age

    def _memory_put(self, partition: str, payload: dict[str, Any]) -> None:
        if self._cfg.topology.cache_ttl_seconds <= 0:
            return
        # The stored entry must not carry a snapshot of the age it had when it
        # was first served; the age is recomputed from ``stored_at`` instead.
        clean = {key: value for key, value in payload.items() if key != "cache_age_seconds"}
        self._memory[partition] = (time.time(), clean)

    async def _drop_pending(self, partition: str, *, cancel: bool) -> None:
        """Forget a queued probe job, optionally cancelling it first.

        Only jobs this service itself submitted can ever be in ``_pending``,
        so cancelling one is safe under a shared account.
        """
        entry = self._pending.pop(partition, None)
        if not entry or not cancel:
            return
        try:
            await self._slurm.cancel(str(entry.get("job_id")))
        except HpcMcpError:
            pass

    async def _remote_cache_lookup(self, partition: str, ttl: float) -> dict[str, Any] | None:
        if ttl <= 0:
            return None
        try:
            read = await self._files.read_file(self._cache_path(partition), max_bytes=256 * 1024)
        except HpcMcpError:
            return None
        except Exception:  # noqa: BLE001 - a missing/corrupt cache is not an error
            return None
        try:
            payload = json.loads(read.get("content") or "")
        except ValueError:
            return None
        if not isinstance(payload, dict) or payload.get("status") != "ok":
            return None
        if payload.get("partition") != partition:
            return None
        collected = payload.get("collected_at_epoch")
        if not isinstance(collected, (int, float)) or isinstance(collected, bool):
            return None
        age = time.time() - float(collected)
        if age < 0 or age > ttl:
            return None
        payload = dict(payload)
        payload["cache_age_seconds"] = round(age, 1)
        return payload

    async def _write_remote_cache(self, partition: str, payload: dict[str, Any]) -> None:
        if self._cfg.topology.cache_ttl_seconds <= 0:
            return
        try:
            await self._files.write_file(self._cache_path(partition), json.dumps(payload, ensure_ascii=False))
        except HpcMcpError:
            # A cache that cannot be persisted is not worth failing the probe.
            return

    async def _write_probe_script(self) -> None:
        await self._files.mkdir(self._topo_dir, parents=True)
        await self._files.write_file(self._script_path, PROBE_SCRIPT)

    async def _query_sinfo(self) -> dict[str, Any]:
        """Partition summary plus distinct per-node hardware variants."""
        configured = list(self._cfg.slurm.allowed_partitions)
        # Partition names end up inside ``sinfo -p`` (comma list), so keep only
        # plain identifiers; anything else is reported, never interpolated.
        allowed = [p for p in configured if isinstance(p, str) and _SAFE_PARTITION_RE.match(p)]
        rejected = [p for p in configured if p not in allowed]
        result: dict[str, Any] = {"available": False, "partitions": [], "node_variants": []}
        if rejected:
            result["error"] = (
                f"{len(rejected)} configured partition name(s) are not plain identifiers and were ignored"
            )
        if not allowed:
            return result
        summary = await self._safe_exec.run(f'sinfo -h -o "{SINFO_PARTITION_FORMAT}"')
        if summary.get("exit_code") != 0:
            result["error"] = (summary.get("stderr") or "").strip()[:500] or "sinfo failed"
            return result
        rows = parse_sinfo_partitions(summary.get("stdout") or "")
        result["partitions"] = [row for row in rows if row["partition"] in allowed]
        query = ",".join(allowed)
        nodes = await self._safe_exec.run(f'sinfo -h -N -p {query} -o "{SINFO_NODE_FORMAT}"')
        if nodes.get("exit_code") == 0:
            variants, rows_seen = parse_sinfo_nodes(nodes.get("stdout") or "")
            result["node_variants"] = variants[:8]
            result["node_rows_seen"] = rows_seen
        result["available"] = True
        return result

    def _sinfo_for(self, sinfo: dict[str, Any], partition: str) -> dict[str, Any] | None:
        for row in sinfo.get("partitions", []):
            if row.get("partition") == partition:
                return row
        return None

    async def _collect(self, partition: str) -> dict[str, Any]:
        sinfo = await self._query_sinfo()
        await self._write_probe_script()
        submitted = await self._slurm.submit(
            job_name=PROBE_JOB_NAME,
            working_directory=self._topo_dir,
            command=["bash", self._script_path],
            partition=partition,
            nodes=1,
            ntasks=1,
            cpus_per_task=1,
            time_limit=self._cfg.topology.collect_time_limit,
        )
        job_id = str(submitted["job_id"])
        try:
            state = await self._slurm.wait(
                job_id,
                timeout_seconds=self._cfg.topology.wait_seconds,
                poll_interval=5,
            )
        except RemoteCommandError:
            self._pending[partition] = {"job_id": job_id, "started": time.monotonic()}
            return {
                "status": "pending",
                "partition": partition,
                "collection_job_id": job_id,
                "job_dir": submitted.get("job_dir"),
                "note": (
                    f"拓扑采集作业 {job_id} 已提交但仍在排队（等待 "
                    f"{self._cfg.topology.wait_seconds}s 未完成）。稍后再次调用会复用它，不会重复提交。"
                ),
                "sinfo": self._sinfo_block(sinfo, partition),
            }
        return await self._finalize(partition, job_id, state, sinfo)

    async def _resume_pending(self, partition: str, pending: dict[str, Any]) -> dict[str, Any] | None:
        """Re-check a queued probe job.  None means "give up and re-collect"."""
        job_id = str(pending.get("job_id"))
        age = time.monotonic() - float(pending.get("started", 0.0))
        try:
            status = await self._slurm.status(job_id)
        except HpcMcpError:
            await self._drop_pending(partition, cancel=False)
            return None
        state = str(status.get("state", "UNKNOWN")).split("+")[0].strip()
        if state in _OK_STATES or state in _BAD_STATES:
            await self._drop_pending(partition, cancel=False)
            sinfo = await self._query_sinfo()
            return await self._finalize(partition, job_id, {"state": state}, sinfo)
        if age > max(60.0, self._cfg.topology.wait_seconds * 4):
            # Give up on a job that has been queued for far too long; free the
            # slot.  Only this service's own probe jobs can reach this path.
            await self._drop_pending(partition, cancel=True)
            return None
        return {
            "status": "pending",
            "partition": partition,
            "collection_job_id": job_id,
            "note": (
                f"拓扑采集作业 {job_id} 仍在队列中（当前状态 {state}，已等待 {round(age)}s）。"
                "稍后再次调用会复用它；如长时间无法调度，请向管理员确认分区可用性。"
            ),
        }

    async def _finalize(
        self,
        partition: str,
        job_id: str,
        state: dict[str, Any],
        sinfo: dict[str, Any],
    ) -> dict[str, Any]:
        final_state = str(state.get("state", "UNKNOWN")).split("+")[0].strip()
        if final_state not in _OK_STATES:
            stderr = ""
            try:
                err = await self._slurm.output(job_id, stream="stderr", tail_bytes=8192)
                stderr = (err.get("content") or "").strip()[:1000]
            except HpcMcpError:
                pass
            raise RemoteCommandError(
                f"Topology probe job {job_id} finished in state {final_state}"
                + (f"; stderr tail: {stderr}" if stderr else "")
                + ". Use hpc.slurm.output / hpc.jobs.diagnose for details."
            )
        out = await self._slurm.output(job_id, tail_bytes=_PROBE_OUTPUT_LIMIT)
        payload = self._build_payload(partition, job_id, out.get("content") or "", sinfo)
        await self._write_remote_cache(partition, payload)
        self._memory_put(partition, payload)
        return {**payload, "source": "probe-job"}

    def _sinfo_block(self, sinfo: dict[str, Any], partition: str) -> dict[str, Any]:
        return {
            "available": bool(sinfo.get("available")),
            "partition": self._sinfo_for(sinfo, partition),
            "node_variants": sinfo.get("node_variants", []),
            "error": sinfo.get("error"),
        }

    def _build_payload(
        self,
        partition: str,
        job_id: str,
        stdout: str,
        sinfo: dict[str, Any],
    ) -> dict[str, Any]:
        sections = split_sections(stdout)
        cpu = parse_lscpu(sections.get("lscpu", ""))
        cpuinfo = parse_cpuinfo(sections.get("cpuinfo", ""))
        numactl = parse_numactl(sections.get("numactl", ""))
        meminfo = parse_meminfo(sections.get("meminfo", ""))
        syscache = parse_sysfs_cache(sections.get("syscache", ""))
        meta = _env_lines(sections.get("meta", ""))
        os_lines = [line.strip() for line in (sections.get("os", "") or "").splitlines() if line.strip()]

        if not cpu or (cpu.get("model_name") is None and cpu.get("logical_cpus") is None):
            # lscpu absent: salvage what /proc/cpuinfo knows.
            cpu = {
                "model_name": cpuinfo.get("model_name"),
                "vendor": cpuinfo.get("vendor"),
                "sockets": None,
                "cores_per_socket": cpuinfo.get("cpu_cores"),
                "threads_per_core": None,
                "physical_cores": None,
                "logical_cpus": cpuinfo.get("siblings"),
                "numa_nodes": None,
                "numa_cpu_lists": {},
                "cache_kib": {},
                "cache_raw": {},
                "flags": cpuinfo.get("flags"),
            }
        cpu["simd"] = summarize_simd(cpu.get("flags"))
        cpu.pop("flags", None)  # the raw flag list is long and not needed twice

        # Cache hierarchy: lscpu is authoritative when it says something;
        # otherwise fall back to /sys (older lscpu builds, many ARM nodes).
        lscpu_cache = cpu.get("cache_kib") or {}
        if any(value for value in lscpu_cache.values()):
            cpu["cache_source"] = "lscpu"
        elif syscache:
            cpu["cache_kib"] = {**{key: None for key in ("l1d", "l1i", "l2", "l3")}, **syscache}
            cpu["cache_source"] = "sysfs"
        else:
            cpu["cache_source"] = None

        numa = {
            "count": numactl.get("count") or cpu.get("numa_nodes"),
            "nodes": numactl.get("nodes") or [
                {"node": int(node), "cpus": spec, "cpus_count": count_cpu_list(spec)}
                for node, spec in (cpu.get("numa_cpu_lists") or {}).items()
            ],
            "distances": numactl.get("distances") or [],
            "source": "numactl" if numactl else ("lscpu" if cpu.get("numa_cpu_lists") else None),
        }

        partition_row = self._sinfo_for(sinfo, partition)
        recommended = recommend_parallel(
            cpu,
            numa,
            meminfo,
            sinfo_partition=partition_row,
            slurm_max_cpus=self._cfg.slurm.max_cpus,
            slurm_max_nodes=self._cfg.slurm.max_nodes,
            slurm_max_time=self._cfg.slurm.max_time,
        )

        notes: list[str] = []
        variants = sinfo.get("node_variants") or []
        if len(variants) > 1:
            notes.append(
                f"该分区的节点不是同构的（{len(variants)} 种硬件组合）：拓扑只代表采样节点 "
                f"{meta.get('SLURMD_NODENAME') or 'unknown'}，用 --constraint 或按节点提交可避免落到不同型号上。"
            )
        if not sections.get("lscpu") or "unavailable lscpu" in (sections.get("lscpu") or ""):
            notes.append("计算节点上没有 lscpu，部分字段来自 /proc/cpuinfo，可能不如 lscpu 完整。")
        if not cpu.get("cache_source"):
            notes.append(
                "该节点没有可用的 cache 层级信息（lscpu 未输出 cache 行，"
                "/sys/devices/system/cpu/cpu0/cache 也不可读）——cache 分块与共享域相关的调优请靠实测确定。"
            )
        if sinfo.get("error"):
            notes.append(f"sinfo 查询失败，Slurm 侧信息缺失：{sinfo['error']}")
        if partition_row and partition_row.get("features") is None:
            notes.append(
                "该分区没有配置 node features（sinfo 显示为空），因此无法用 --constraint 按微架构选节点；"
                "扩容到异构分区时请显式指定节点或向管理员申请 features 标签。"
            )

        return {
            "status": "ok",
            "partition": partition,
            "collected_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "collected_at_epoch": time.time(),
            "collection_job_id": job_id,
            "collected_on_node": meta.get("SLURMD_NODENAME"),
            "cpu": cpu,
            "numa": numa,
            "cache_kib": cpu.get("cache_kib"),
            "memory_mib": {
                "mem_total": meminfo.get("memtotal"),
                "mem_free": meminfo.get("memfree"),
                "mem_available": meminfo.get("memavailable"),
                "hugepage_size": meminfo.get("hugepagesize"),
            },
            "os": {
                "system": os_lines[0] if len(os_lines) > 0 else None,
                "machine": os_lines[1] if len(os_lines) > 1 else None,
                "kernel": os_lines[2] if len(os_lines) > 2 else None,
            },
            "slurm": {
                **self._sinfo_block(sinfo, partition),
                "node_rows_seen": sinfo.get("node_rows_seen"),
            },
            "job_environment": {
                "cpus_on_node": _as_int(meta.get("SLURM_CPUS_ON_NODE")),
                "mem_per_node_mb": _as_int(meta.get("SLURM_MEM_PER_NODE")),
            },
            "recommended_parallel_parameters": recommended,
            "notes": notes,
        }
